FROM ubuntu:trusty
#Thanks to https://github.com/bydavy/docker-plex/blob/master/Dockerfile and https://github.com/aostanin/docker-plex/blob/master/Dockerfile. Adapted from https://github.com/timhaak/docker-plex
# Installs the non-plexpass version from the the PPA
MAINTAINER Scott Hansen <firecat4153@gmail.com>

RUN apt-get -q update && apt-get install -qy --force-yes curl unzip

RUN echo "deb http://shell.ninthgate.se/packages/debian squeeze main" > /etc/apt/sources.list.d/plexmediaserver.list

RUN curl http://shell.ninthgate.se/packages/shell-ninthgate-se-keyring.key | apt-key add -

RUN apt-get -q update && apt-get install -qy --force-yes plexmediaserver

# Fixes a problem where avahi won't start inside the container
RUN sed -i "s/rlimit-nproc=3/#rlimit-nproc=3/" /etc/avahi/avahi-daemon.conf

VOLUME /config

ADD ./start.sh /start.sh
RUN chmod u+x  /start.sh

EXPOSE 32400:32400 32443:32443 1900:1900/udp 32463:32463 5353:5353/udp 32410:32410/udp 32412:32412/udp 32413:32413/udp 32414:32414/udp

CMD ["/start.sh"]
