ARG ALPINE_LINUX_VERSION="3.18"

FROM docker.io/library/golang:1-alpine${ALPINE_LINUX_VERSION} as build
WORKDIR /go/src/
RUN apk add --no-cache --update btrfs-progs-dev build-base curl device-mapper-libs git gpgme-dev lvm2-dev && \
    git clone https://github.com/containers/prometheus-podman-exporter.git . && \
    make binary

FROM docker.io/library/alpine:${ALPINE_LINUX_VERSION}
RUN apk --no-cache add gpgme lvm2
COPY --from=build /go/src/bin/prometheus-podman-exporter /usr/local/bin/prometheus-podman-exporter
EXPOSE 9882
CMD ["prometheus-podman-exporter", "--collector.enable-all"]
