#!/bin/bash
# This script sets up the postgres database for the first time.
# Admin password can be set in ./postgres_password or $HOME/.postgres_password

docker rm postgres_temp
docker run -it --volumes-from postgres_data --name postgres_temp postgres:latest \
    [ -d /var/lib/postgresql/data/base ] || {

        # Check for POSTGRES_PASSWORD. If it's not there then attempt to import
        # the password from ./postgres_password or ~/.postgres_password
        if [[ -z $POSTGRES_PASSWORD ]]; then
            if [[ -f postgres_password ]]; then
                export $(cat postgres_password|grep -v ^#|xargs)
            elif [[ -f $HOME/.postgres_password ]]; then
                export "$(cat $HOME/.postgres_password|grep -v ^#|xargs)"
            fi
        fi
        if [[ -z $POSTGRES_PASSWORD ]]; then
            echo "You need to set POSTGRES_PASSWORD to initialize the database"
            docker rm postgres_temp
            exit 1
        fi

        # Create the data volume
        docker run -v /var/lib/postgresql/data \
            --name postgres_data \
            busybox true

        # Initialize the database
        docker run -d -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
            --volumes-from postgres_data \
            --name postgres_run \
            postgres:latest

        sleep 10

        docker stop postgres_run && docker rm postgres_run
}
docker rm postgres_temp
exit 0
